Abort-Cause:
  '0': BEARER_RELEASED
  '1': INSUFFICIENT_SERVER_RESOURCES
  '2': INSUFFICIENT_BEARER_RESOURCES
  '3': PS_TO_CS_HANDOVER
  '4': SPONSORED_DATA_CONNECTIVITY_DISALLOWED
Event-Trigger:
  '0': SGSN_CHANGE
  '1': QOS_CHANGE
  '2': RAT_CHANGE
  '3': TFT_CHANGE
  '4': PLMN_CHANGE
  '5': LOSS_OF_BEARER
  '6': RECOVERY_OF_BEARER
  '7': IP-CAN_CHANGE
  '11': QOS_CHANGE_EXCEEDING_AUTHORIZATION
  '12': RAI_CHANGE
  '13': USER_LOCATION_CHANGE
  '14': NO_EVENT_TRIGGERS
  '15': OUT_OF_CREDIT
  '16': REALLOCATION_OF_CREDIT
  '17': REVALIDATION_TIMEOUT
  '18': UE_IP_ADDRESS_ALLOCATE
  '19': UE_IP_ADDRESS_RELEASE
  '20': DEFAULT_EPS_BEARER_QOS_CHANGE
  '21': AN_GW_CHANGE
  '22': SUCCESSFUL_RESOURCE_ALLOCATION
  '23': RESOURCE_MODIFICATION_REQUEST
  '24': PGW_TRACE_CONTROL
  '25': UE_TIME_ZONE_CHANGE
Flow-Usage:
  '0': NO_INFORMATION
  '1': RTCP
  '2': AF_SIGNALLING
IP-CAN-Type:
  '0': 3GPP-GPRS
  '1': DOCSIS
  '2': xDSL
  '3': WiMAX
  '4': 3GPP2
  '5': 3GPP-EPS
  '6': Non-3GPP-EPS
Media-Type:
  '0': AUDIO
  '1': VIDEO
  '2': DATA
PCC-Rule-Status:
  '0': ACTIVE
  '1': INACTIVE
  '2': TEMPORARILY INACTIVE
RAT-Type:
  '0': WLAN
  '1000': UTRAN
  '1001': GERAN
  '1002': GAN
  '1003': HSPA-Evolution
  '1004': EUTRAN
Rule-Failure-Code:
  '1': UNKNOWN_RULE_NAME
  '2': RATING_GROUP_ERROR
  '3': SERVICE_IDENTIFIER_ERROR
  '4': GW/PCEF_MALFUNCTION
  '5': RESOURCES_LIMITATION
  '6': MAX_NR_BEARERS_REACHED
  '7': UNKNOWN_BEARER_ID
  '8': MISSING_BEARER_ID
  '9': MISSING_FLOW_DESCRIPTION
  '13': PS_TO_CS_HANDOVER
SIP-Forking-Indication:
  '0': SINGLE_DIALOGUE
  '1': SEVERAL_DIALOGUES
Specific-Action:
  '0': SERVICE_INFORMATION_REQUEST
  '1': CHARGING_CORRELATION_EXCHANGE
  '2': INDICATION_OF_LOSS_OF_BEARER
  '3': INDICATION_OF_RECOVERY_OF_BEARER
  '4': INDICATION_OF_RELEASE_OF_BEARER
  '5': INDICATION_OF_ESTABLISHMENT_OF_BEARER
  '6': IP-CAN_CHANGE
Termination-Cause:
  '1': DIAMETER LOGOUT
  '2': DIAMETER SERVICE NOT PROVIDED
  '3': DIAMETER BAD ANSWER
  '4': DIAMETER ADMINISTRATIVE
  '5': DIAMETER LINK BROKEN
  '6': DIAMETER AUTH EXPIRED
  '7': DIAMETER USER MOVED
  '8': DIAMETER SESSION TIMEOUT
SL-Request-Type:
  '0': INITIAL_REQUEST
  '1': UPDATE_REQUEST
  '2': TERMINATION_REQUEST