@startuml
package DiamTelecom {
    class DiameterMessage <<DiamTelecom>> {
        +app_id: int
        +command_code: int
        +is_request: bool
        +cc_request_type: int
        +message: Message
    }

    class DiameterMessages <<DiamTelecom>> {
    }

    DiameterMessages o-- DiameterMessage
}
@enduml
