@startuml
!include message.puml

package DiamTelecom {
    class DiameterSession <<DiamTelecom>> {
        +session_id: str
        +messages: DiameterMessages
    }

    DiameterSession *-- DiameterMessages

    class DiameterSessions <<DiamTelecom>> {
        +sessions: Map[str, DiameterSession]
        +create() -> DiameterSession
    }

    DiameterSessions o-- DiameterSession

    class GxSession <<DiamTelecom>> {
        +framed_ip_address: str
    }

    class GxSessions <<DiamTelecom>> {
        +create() -> GxSession
    }

    GxSessions --|> DiameterSessions
    GxSession --|> DiameterSession
    GxSessions o-- GxSession

    class RxSession <<DiamTelecom>> {
        +gx_session_id: str
    }

    class RxSessions <<DiamTelecom>> {
        +create() -> RxSession
    }

    RxSessions --|> DiameterSessions
    RxSession --|> DiameterSession
    RxSessions o-- RxSession

    class SySession <<DiamTelecom>> {
        +gx_session_id: str
    }

    class SySessions <<DiamTelecom>> {
        +create() -> SySession
    }
    SySessions --|> DiameterSessions
    SySession --|> DiameterSession
    SySessions o-- SySession



}
@enduml
